sudo: required
services:
  - docker

#install:
#  - bundle install

before_install:
  - docker build -t docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true docker-react npm run test -- --coverage
